/**
 * Abbreviations the documents use, spelled out. Prose rendered through the
 * markdown components marks the first use of each one per section and shows
 * the expansion on hover (see `lib/rehype-abbr.ts`).
 *
 * Keys are matched case-sensitively on word boundaries, and a trailing plural
 * "s" is covered by the singular entry, so "CDNs" needs no key of its own.
 *
 * `npm run check:abbr` fails on any abbreviation in `content/` that is neither
 * here nor in `NOT_ABBREVIATIONS` below, so a new one can't ship unexplained.
 */
export const GLOSSARY: Record<string, string> = {
  ABR: "Adaptive bitrate streaming",
  ACID: "Atomicity, Consistency, Isolation, Durability",
  AOF: "Append-only file (Redis persistence)",
  AP: "Available and partition-tolerant (a CAP theorem choice)",
  APNs: "Apple Push Notification service",
  ASN: "Autonomous system number (a network operator's routing ID)",
  AV1: "AOMedia Video 1, a royalty-free video codec",
  AVL: "Adelson-Velsky and Landis, a self-balancing binary search tree",
  AWS: "Amazon Web Services",
  AZ: "Availability zone",
  BASE: "Basically available, soft state, eventually consistent",
  BCR: "Best conceivable runtime — the fastest any algorithm for a problem could run",
  BFF: "Backend for frontend",
  BFS: "Breadth-first search",
  BM25: "Best Match 25, a search relevance ranking function",
  BUD: "Bottlenecks, unnecessary work, duplicated work — the interview method for finding optimizations",
  BRIN: "Block range index (Postgres)",
  BST: "Binary search tree",
  CEO: "Chief executive officer",
  CAP: "Consistency, availability, partition tolerance",
  CAPTCHA: "Completely Automated Public Turing test to tell Computers and Humans Apart",
  CDC: "Change data capture",
  CDN: "Content delivery network",
  CI: "Continuous integration",
  CMAF: "Common Media Application Format",
  CMS: "Content management system",
  CP: "Consistent and partition-tolerant (a CAP theorem choice)",
  CQRS: "Command Query Responsibility Segregation",
  CRDT: "Conflict-free replicated data type",
  CTO: "Chief technology officer",
  DIP: "Dependency inversion principle — depend on abstractions, not concrete details",
  DIY: "Do it yourself — solve the problem manually, then turn your own process into the algorithm",
  DTO: "Data transfer object — a structure with public fields and no behavior, for wire or database formats",
  CTR: "Click-through rate",
  DAG: "Directed acyclic graph",
  DASH: "Dynamic Adaptive Streaming over HTTP",
  DAU: "Daily active users",
  DAWG: "Directed acyclic word graph",
  DDL: "Data definition language (schema statements)",
  DDoS: "Distributed denial of service",
  DFS: "Depth-first search",
  DLQ: "Dead letter queue",
  DM: "Direct message",
  DNS: "Domain Name System",
  DOM: "Document Object Model",
  DP: "Dynamic programming",
  DRM: "Digital rights management",
  E2E: "End-to-end",
  E2EE: "End-to-end encryption",
  ETA: "Estimated time of arrival",
  ETag: "Entity tag, an HTTP cache validator",
  ETL: "Extract, transform, load",
  EJB: "Enterprise JavaBeans — Java's early server-side component model",
  EXIF: "Exchangeable Image File Format (photo metadata)",
  FCM: "Firebase Cloud Messaging (Google's push service)",
  FIFO: "First in, first out",
  LIFO: "Last in, first out",
  FX: "Foreign exchange",
  GA: "General admission (unreserved seating)",
  GC: "Garbage collection",
  GCS: "Google Cloud Storage",
  GDPR: "General Data Protection Regulation (EU privacy law)",
  GIN: "Generalized inverted index (Postgres)",
  GiST: "Generalized search tree (Postgres)",
  GPS: "Global Positioning System",
  GSI: "Global secondary index (DynamoDB)",
  HDD: "Hard disk drive",
  HDR: "High dynamic range",
  HLL: "HyperLogLog",
  HLS: "HTTP Live Streaming",
  HMAC: "Hash-based message authentication code",
  HSB: "Hue, saturation, brightness — the color model most design software shows",
  HSL: "Hue, saturation, lightness — the color format browsers understand",
  IO: "Input/output",
  ISP: "Internet service provider",
  JSONB: "Binary JSON (a Postgres column type)",
  JWT: "JSON Web Token",
  KMS: "Key management service",
  KRaft: "Kafka Raft, Kafka's built-in metadata quorum",
  KV: "Key-value",
  LCS: "Longest common subsequence",
  LFU: "Least frequently used",
  "LL-HLS": "Low-Latency HTTP Live Streaming",
  LLM: "Large language model",
  LCA: "Lowest common ancestor (the closest shared ancestor of two nodes)",
  LRU: "Least recently used",
  LSH: "Locality-sensitive hashing",
  LSI: "Local secondary index (DynamoDB)",
  LSM: "Log-structured merge (tree)",
  LWW: "Last write wins",
  MD5: "Message Digest 5, a hash function",
  ML: "Machine learning",
  MRU: "Most recently used",
  MVCC: "Multi-version concurrency control",
  mTLS: "Mutual TLS: both sides of the connection present a certificate",
  NAT: "Network address translation",
  NoSQL: "Non-relational database (“not only SQL”)",
  NTP: "Network Time Protocol",
  OLAP: "Online analytical processing",
  OLTP: "Online transaction processing",
  OOM: "Out of memory",
  OCP: "Open-closed principle — open for extension, closed for modification",
  OT: "Operational transformation",
  PACELC: "If partitioned: availability or consistency; else: latency or consistency",
  PAN: "Primary account number (the card number)",
  PCI: "Payment Card Industry",
  "PCI-DSS": "Payment Card Industry Data Security Standard",
  PII: "Personally identifiable information",
  PK: "Primary key (in DynamoDB-style tables, the partition key)",
  PoP: "Point of presence, a CDN edge location",
  PR: "Pull request",
  PSP: "Payment service provider",
  QoE: "Quality of experience",
  QPS: "Queries per second",
  QA: "Quality assurance",
  SAR: "Situation, action, result — the structure of a behavioral interview answer",
  RDB: "Redis Database file (a point-in-time snapshot)",
  RGB: "Red, green, blue — a color as mixes of light",
  REST: "Representational state transfer",
  RPC: "Remote procedure call",
  RPO: "Recovery point objective: how much data you can lose",
  RTO: "Recovery time objective: how long you can be down",
  SaaS: "Software as a service",
  SDK: "Software development kit",
  SDET: "Software development engineer in test",
  SHA: "Secure Hash Algorithm",
  "SHA-256": "Secure Hash Algorithm, 256-bit",
  SK: "Sort key",
  SLA: "Service level agreement",
  SPOF: "Single point of failure — a component whose failure takes the whole system down",
  SLI: "Service level indicator",
  SLO: "Service level objective",
  SMS: "Short Message Service (text messages)",
  SMTP: "Simple Mail Transfer Protocol",
  SNS: "Amazon Simple Notification Service",
  SPA: "Single-page application",
  SQS: "Amazon Simple Queue Service",
  SSD: "Solid-state drive",
  SSE: "Server-sent events",
  SST: "Sorted string table",
  SSTable: "Sorted string table",
  SWIM: "Scalable Weakly-consistent Infection-style Membership protocol",
  TCP: "Transmission Control Protocol",
  "TF-IDF": "Term frequency × inverse document frequency",
  TLS: "Transport Layer Security",
  TP1: "Transformation property 1 (an OT convergence condition)",
  TP2: "Transformation property 2 (an OT convergence condition)",
  TTL: "Time to live",
  TDD: "Test-driven development",
  UUID: "Universally unique identifier",
  VP: "Vice president",
  WAF: "Web application firewall",
  WAL: "Write-ahead log",
  WCAG: "Web Content Accessibility Guidelines",
  WARC: "Web ARChive, the crawl archive file format",
  WebRTC: "Web Real-Time Communication",
  WS: "WebSocket",
  WSS: "WebSocket Secure (WebSocket over TLS)",
  XOR: "Exclusive or",
  ZAB: "ZooKeeper Atomic Broadcast",
  p50: "50th percentile latency (the median)",
  p80: "80th percentile latency",
  p95: "95th percentile latency",
  p99: "99th percentile latency",
  "p99.9": "99.9th percentile latency",
};

/**
 * Tokens shaped like abbreviations that are deliberately left unmarked: terms
 * every reader of this site already knows, units, SQL and HTTP keywords, and
 * words written in capitals for emphasis or as state names. Only
 * `npm run check:abbr` reads this.
 */
export const NOT_ABBREVIATIONS: string[] = [
  // Known to anyone reading about system design.
  "API", "CPU", "CSS", "DB", "HTML", "HTTP", "HTTPS", "ID", "IP", "JS", "JSON", "OS", "PDF", "RAM",
  "SQL", "UI", "URL", "UX",
  // Units and places.
  "GB", "KB", "MB", "PB", "TB", "EU", "UK", "US",
  // Code identifiers in scraped starter code, not abbreviations.
  "BANC", "LRUCache", "ADOBECODEBANC", "ABC",
  // Names of products and projects, not abbreviations to expand.
  "gRPC", "InnoDB", "iOS", "MySQL", "PostGIS", "TinyURL",
  // Not abbreviations at all.
  "ISO", "II", "III", "IV", "VI", "VII", "VIII", "OK",
  // This site's own name, and words capitalized for emphasis or structure.
  "CE", "TODO",
  // Statement, command and state names, written as the system spells them.
  "AND", "DESC", "GEOSEARCH", "HIT", "INSERT", "LISTEN", "MISS", "NOT", "NOTIFY", "OR", "PENDING", "POST",
  "PUT", "QUORUM", "RATE", "SET", "SNAPSHOTS", "UNIQUE", "UPDATE",
];
